"""Configure the style settings for mplfinance plots."""

style = {'base_mpl_style': 'default',
         'marketcolors': {'candle': {'up': '#00b060',
                                     'down': '#fe3032'},
                          'edge': {'up': '#00b060',
                                   'down': '#fe3032'},
                          'wick': {'up': '#00b060',
                                   'down': '#fe3032'},
                          'ohlc': {'up': '#00b060',
                                   'down': '#fe3032'},
                          'volume': {'up': '#00b060',
                                     'down': '#fe3032'},
                          'vcedge': {'up': '#00b060',
                                     'down': '#fe3032'},
                          'vcdopcod': None,
                          'alpha': None},
         'mavcolors': ['#ff7f0e',
                       '#1f77b4',
                       '#e377c2'],
         'facecolor': '#fafafa',
         'figcolor': 'white',
         'gridcolor': '#d0d0d0',
         'gridstyle': '-',
         'y_on_right': None,
         'rc': {'axes.edgecolor': '#f0f0f0',
                'axes.labelcolor': '#101010',
                'figure.titlesize': 'x-large',
                'figure.titleweight': 'semibold',
                'text.color': 'black',
                'xtick.color': '#101010',
                'ytick.color': '#101010'},
         # The mplfinance._styledata module does not use the following
         # custom keys.
         'tg_tooltip_color': 'white',
         'tg_neutral_color': 'black',
         'tg_profit_color': '#00b060',
         'tg_loss_color': '#fe3032'}
